### ISSUE TITLE
Plugin doesn't work with Nexus 2.7.0-04

### ISSUE THREAD

**Issue by ivadim** [sonatype/nexus-ruby-support#47]
Today I've tried to install plugin to nexus oss(and nexus pro) 2.7.0-04. But without success. Signature of one core method might have been changed.

When I try to added new Hosted rubygem repo I got next error:

```
jvm 1    | 2013-11-28 20:18:09 ERROR [qtp198808983-33] admin org.sonatype.nexus.rest.NexusApplication - Unhandled exception or error intercepted
jvm 1    | java.lang.NoSuchMethodError: org.sonatype.nexus.proxy.item.PreparedContentLocator.<init>(Ljava/io/InputStream;Ljava/lang/String;)V
jvm 1    |      at org.sonatype.nexus.plugins.ruby.fs.RubyFSLocalRepositoryStorage.storeSpecsIndex(RubyFSLocalRepositoryStorage.java:319) ~[na:na]
jvm 1    |      at org.sonatype.nexus.plugins.ruby.hosted.HostedRubygemsFacade.createEmptySpecs(HostedRubygemsFacade.java:120) ~[na:na]
jvm 1    |      at org.sonatype.nexus.plugins.ruby.hosted.HostedRubygemsFacade.retrieveSpecsIndex(HostedRubygemsFacade.java:142) ~[na:na]
jvm 1    |      at org.sonatype.nexus.plugins.ruby.hosted.DefaultHostedRubyRepository.doConfigure(DefaultHostedRubyRepository.java:70) ~[na:na]
jvm 1    |      at org.sonatype.nexus.configuration.AbstractConfigurable.configure(AbstractConfigurable.java:168) ~[nexus-core-2.7.0-04.jar:2.7.0-04]
jvm 1    |      at org.sonatype.nexus.configuration.application.DefaultNexusConfiguration.instantiateRepository(DefaultNexusConfiguration.java:781) ~[nexus-core-2.7.0-04.jar:2.7.0-04]
jvm 1    |      at org.sonatype.nexus.configuration.application.DefaultNexusConfiguration.instantiateRepository(DefaultNexusConfiguration.java:765) ~[nexus-core-2.7.0-04.jar:2.7.0-04]
jvm 1    |      at org.sonatype.nexus.configuration.application.DefaultNexusConfiguration.createRepository(DefaultNexusConfiguration.java:943) ~[nexus-core-2.7.0-04.jar:2.7.0-04]
jvm 1    |      at org.sonatype.nexus.templates.repository.AbstractRepositoryTemplateProvider.createRepository(AbstractRepositoryTemplateProvider.java:67) ~[nexus-core-2.7.0-04.jar:2.7.0-04]
jvm 1    |      at org.sonatype.nexus.templates.repository.AbstractRepositoryTemplate.create(AbstractRepositoryTemplate.java:101) ~[nexus-core-2.7.0-04.jar:2.7.0-04]
jvm 1    |      at org.sonatype.nexus.rest.repositories.RepositoryListPlexusResource.post(RepositoryListPlexusResource.java:146) ~[na:na]
jvm 1    |      at org.sonatype.plexus.rest.resource.RestletResource.acceptRepresentation(RestletResource.java:271) ~[na:na]
jvm 1    |      at org.sonatype.nexus.rest.NexusRestletResource.acceptRepresentation(NexusRestletResource.java:71) ~[na:na]
jvm 1    |      at org.restlet.resource.Resource.post(Resource.java:688) ~[na:na]
jvm 1    |      at org.restlet.resource.Resource.handlePost(Resource.java:537) ~[na:na]
jvm 1    |      at org.restlet.Finder.handle(Finder.java:357) ~[na:na]
jvm 1    |      at org.restlet.Filter.doHandle(Filter.java:150) ~[na:na]
jvm 1    |      at org.restlet.Filter.handle(Filter.java:195) ~[na:na]
```

Plugin was built with maven 3.0.4 on Debian 7.1
mvn clean install -Dnexus.version=2.7.0-04 -Dmaven.test.skip

P.s Is there any email-lists about this plugin where question could be posted?
